# Generated by Django 3.0 on 2022-04-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='university.Homework', verbose_name='домашняя работа'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
    ]
