# Generated by Django 3.0 on 2022-04-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20220401_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='university.Homework', verbose_name='домашняя работа'),
        ),
    ]
