# Generated by Django 4.0 on 2022-05-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_description_alter_anime_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='description',
        ),
        migrations.AddField(
            model_name='description',
            name='anime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='аниме'),
        ),
    ]
